//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public int Priority { get; set; }
        public Nullable<int> ActivId { get; set; }
        public string File { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ExecutorId { get; set; }
        public int LifecycleId { get; set; }
    
        public virtual Activ Activ { get; set; }
        public virtual Category Category { get; set; }
        public virtual Lifecycle Lifecycle { get; set; }
        public virtual User User { get; set; }
    }
}
